// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/pvz.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/pvz.go -destination=internal/repository/mocks/pvz.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	response "github.com/alexey-shedrin/avito-test-task/internal/model/dto/response"
	entity "github.com/alexey-shedrin/avito-test-task/internal/model/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPVZRepository is a mock of PVZRepository interface.
type MockPVZRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPVZRepositoryMockRecorder
	isgomock struct{}
}

// MockPVZRepositoryMockRecorder is the mock recorder for MockPVZRepository.
type MockPVZRepositoryMockRecorder struct {
	mock *MockPVZRepository
}

// NewMockPVZRepository creates a new mock instance.
func NewMockPVZRepository(ctrl *gomock.Controller) *MockPVZRepository {
	mock := &MockPVZRepository{ctrl: ctrl}
	mock.recorder = &MockPVZRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPVZRepository) EXPECT() *MockPVZRepositoryMockRecorder {
	return m.recorder
}

// CreatePvz mocks base method.
func (m *MockPVZRepository) CreatePvz(pvz *entity.Pvz) (*entity.Pvz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePvz", pvz)
	ret0, _ := ret[0].(*entity.Pvz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePvz indicates an expected call of CreatePvz.
func (mr *MockPVZRepositoryMockRecorder) CreatePvz(pvz any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePvz", reflect.TypeOf((*MockPVZRepository)(nil).CreatePvz), pvz)
}

// GetPvz mocks base method.
func (m *MockPVZRepository) GetPvz(startDate, endDate *time.Time, page, limit *int) ([]response.PvzInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPvz", startDate, endDate, page, limit)
	ret0, _ := ret[0].([]response.PvzInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPvz indicates an expected call of GetPvz.
func (mr *MockPVZRepositoryMockRecorder) GetPvz(startDate, endDate, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPvz", reflect.TypeOf((*MockPVZRepository)(nil).GetPvz), startDate, endDate, page, limit)
}
